### ISSUE TITLE
kabstract fails to abstract defeq expressions

### ISSUE THREAD

**Issue by JLimperg** [leanprover-community/lean#302]
MWE:

```lean
open tactic

lemma test (n : ℕ) : n + 1 = nat.succ n :=
begin
  (do n ← get_local `n,
      is_def_eq `(%%n + 1) `(nat.succ %%n) transparency.all ff,
      tgt ← target,
      kabstract tgt `(%%n + 1) transparency.all ff >>= trace,
      kabstract tgt `(nat.succ %%n) transparency.all ff >>= trace
  ),
  sorry
end
```

This prints `#0 = nat.succ n` for the first `kabstract` and `n + 1 = #0` for the second. Afaict, both should be `#0 = #0` since `nat.succ n` and `n + 1` are definitionally equal at the given transparency (as demonstrated by the `is_def_eq`).

Lean version: 3.15.0.

**Comment by gebner** [comment]
This is the expected behavior.  The `kabstract` function works on a similar principle as the simplifier: the head symbol needs to be the same and the arguments are unified using reducible transparency.  You could do `add_key_equivalence has_add.add nat.succ` to make `kabstract` try to unify `+` and `.succ`.  But I'm not sure if that's a good idea.

**Comment by JLimperg** [comment]
Ah okay, thanks for the explanation. A bit annoying for my application, but I guess the users will have to live with that.
