### ISSUE TITLE
The `a` bug

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover-community/lean#437]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The famous `a` bug doesn't need a description, we have all met it.

### Steps to Reproduce

```lean
example (a : ℕ)  : true :=
begin
  have : ∀ n, n ≥ 0 →  a ≤ a,
  sorry
end
```
**Expected behavior:** [What you expect to happen]

No error.

**Actual behavior:** [What actually happens]

Lean chooses the name `a` for the premise `n ≥ 0` and confuses itself.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Lean (version 3.18.4, commit f539be1e867c, Release)

**Comment by rwbarton** [comment]
I think what's going on is something like this:

* The [default name](https://github.com/leanprover-community/lean/blob/a28b9c8f78d982a4e82b1e4f7ce7988d87183ae8/src/kernel/expr.cpp#L924) used for, among other things, [the binder in an arrow type](https://github.com/leanprover-community/lean/blob/a28b9c8f78d982a4e82b1e4f7ce7988d87183ae8/src/kernel/expr.cpp#L702-L704) is `a`.

* The parser has a [mode](https://github.com/leanprover-community/lean/blob/a28b9c8f78d982a4e82b1e4f7ce7988d87183ae8/src/frontends/lean/parser_state.h#L25) variable which controls how identifiers are processed. This mode differs depending on whether or not we are parsing a tactic (see link for documentation).

* When not parsing a tactic, the parser knows what variables are in scope and it can resolve a name like `a` to a local constant or a de Bruijn-indexed variable correctly. I haven't tried to find out how this scope information is maintained, but I assume the context is not extended when we process a `→`.

* Tactics, however, are parsed entirely before being run, and so the parser cannot know what variables will be in scope when it is parsing an expression, because the proof state at that point is not yet known. So instead the parser emits some kind of placeholder containing the textual name, and the reference is resolved at a later time to whatever is in scope at that position. If the name happens to be `a`, then it can pick up a variable that came from an enclosing `→` because the parser created an expression with a binder named `a`.

The right fix would probably be to add some kind of flag on binders which disqualifies them as candidates for the resolution of user-written names which occurs in the last paragraph.

This seems too complicated for the Lean 3 time frame, so I propose to just have the parser instead use the binder name `_a` when it parses `→`. This would have the following user-visible effects (in addition to fixing the example):
* In `example : true → true := begin intro, end` the variable introduced will be named `_a` not `a`. This could break some existing proofs but I don't think it's a big concern--better not to rely on autogenerated names anyways.
* The name `_a` might appear in `a` in some Lean messages (I will try to determine when this happens).
* [Possibly more cases to be added as I go through the test output.]

**Comment by digama0** [comment]
I suggest `_x` instead, which is already used as the base name for `\lam _, ...` binders. I don't see a good reason to have a separate naming system for arrow variables.

**Comment by jcommelin** [comment]
how about `__deadbeef`?

**Comment by rwbarton** [comment]
I edited my earlier comment to use `_x` and to expand the list of visible side effects. PR is #442.

**Comment by rwbarton** [comment]
Unfortunately the renaming to `_x` unearthed another bug, #447.

There is an old Lean issue which is essentially the same as this one: https://github.com/leanprover/lean/pull/1844. But it doesn't contain much beyond what's here.

In view of #447, Kevin and Johan have suggested instead changing the name to something like `xyzzy`. It should be noted that either change will require modifications to some proofs in mathlib (mostly in situations like `cases h`, then using `h_a`). But last I heard Lean 4 won't allow using autogenerated names (by default?) and if so we'd have to modify these proofs eventually anyways.

**Comment by gebner** [comment]
A random unmentionable name sounds good to me as well.  (Although `xyzzy` could refer to a certain monomial...)

**Comment by jcommelin** [comment]
So... `deadbeef`?

**Comment by rwbarton** [comment]
I'll just say that based on my experience testing the change from `a` to `_x`, I'd say there's at least a 50% chance that whatever name we pick will end up in mathlib (at least temporarily) as it will be too annoying to try to avoid using autogenerated names completely.

**Comment by jcommelin** [comment]
I agree with Reid. So, instead of `xyzzy` or `deadbeef`. How about `fixme`?

**Comment by digama0** [comment]
My vote is still for `_x`. I would like to keep the length of autogenerated names down, because I'm sure I will see it 50 times per medium sized tactic state. Seeing `fixme` scrawled all over my tactic state obscuring the actual content, sounds like a bad idea.

What about a funny unicode character? That can keep the visible size down while also making it hard to type, which should help to discourage explicit use in proofs.

**Comment by jcommelin** [comment]
`_x🚫`

**Comment by digama0** [comment]
Can we do 1 character? If it's going to be shorter than _x it has to be 1 character. Keep in mind that this will be extensively prefixed, you can get things like `h_⚠️_1_1_2_⚠️_3` if the base name is `⚠️`

**Comment by jcommelin** [comment]
Ooh sure, fine with me

**Comment by gebner** [comment]
We can't have underscores, so you need to choose between `🚫`, `⚠️`, `⛔`, or `🐄`.

> Seeing fixme scrawled all over my tactic state obscuring the actual content, sounds like a bad idea.

I don't expect you'd see it anywhere.  The pretty printer would print `∀ deadbeef : ℕ, ℕ` as  `ℕ → ℕ`.

**Comment by digama0** [comment]
If I do `intros` or `induction` it's not hard to get in the situation where there are lots of autogenerated variables in the tactic state, many of which I won't need to refer to. These variables then appear in the types of hypotheses in the goal, hence "scrawled all over my tactic state".

Regarding the bikeshed, I would prefer it not colored. Maybe a simple symbol like a diamond `⬥`? Does it have to be an identifier character, lest it get french quoted? Because that will probably limit our choices considerably.

**Comment by gebner** [comment]
> Does it have to be an identifier character, lest it get french quoted?

Good point.  Here are some suggestions for single characters that do not need to be quoted:
```
#eval list.as_string $ (list.range' 0x3ca (0x3fb - 0x3ca)).map char.of_nat
-- "ϊϋόύώϏϐϑϒϓϔϕϖϗϘϙϚϛϜϝϞϟϠϡϢϣϤϥϦϧϨϩϪϫϬϭϮϯϰϱϲϳϴϵ϶ϷϸϹϺ"
#eval list.as_string $ (list.range' 0x1f00 (0x1ffe - 0x1f00)).map char.of_nat
-- "ἀἁἂἃἄἅἆἇἈἉἊἋἌἍἎἏἐἑἒἓἔἕ἖἗ἘἙἚἛἜἝ἞἟ἠἡἢἣἤἥἦἧἨἩἪἫἬἭἮἯἰἱἲἳἴἵἶἷἸἹἺἻἼἽἾἿὀὁὂὃὄὅ὆὇ὈὉὊὋὌὍ὎὏ὐὑὒὓὔὕὖὗ὘Ὑ὚Ὓ὜Ὕ὞ὟὠὡὢὣὤὥὦὧὨὩὪὫὬὭὮὯὰάὲέὴήὶίὸόὺύὼώ὾὿ᾀᾁᾂᾃᾄᾅᾆᾇᾈᾉᾊᾋᾌᾍᾎᾏᾐᾑᾒᾓᾔᾕᾖᾗᾘᾙᾚᾛᾜᾝᾞᾟᾠᾡᾢᾣᾤᾥᾦᾧᾨᾩᾪᾫᾬᾭᾮᾯᾰᾱᾲᾳᾴ᾵ᾶᾷᾸᾹᾺΆᾼ᾽ι᾿῀῁ῂῃῄ῅ῆῇῈΈῊΉῌ῍῎῏ῐῑῒΐ῔῕ῖῗῘῙῚΊ῜῝῞῟ῠῡῢΰῤῥῦῧῨῩῪΎῬ῭΅`῰῱ῲῳῴ῵ῶῷῸΌῺΏῼ´"
#eval list.as_string $ (list.range' 0x2100 (0x214f - 0x2100)).map char.of_nat
-- "℀℁ℂ℃℄℅℆ℇ℈℉ℊℋℌℍℎℏℐℑℒℓ℔ℕ№℗℘ℙℚℛℜℝ℞℟℠℡™℣ℤ℥Ω℧ℨ℩KÅℬℭ℮ℯℰℱℲℳℴℵℶℷℸℹ℺℻ℼℽℾℿ⅀⅁⅂⅃⅄ⅅⅆⅇⅈⅉ⅊⅋⅌⅍ⅎ"
```

I did not know that you could use `℻` as a variable name without french-quoting it.

**Comment by jcommelin** [comment]
So we use `ᾰ`, and then we can replace the `a`-bug with the `ᾰ`-bug :smile_cat:
