### ISSUE TITLE
Bug with destructive let in equation compiler

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/lean#55]
Zulip topic: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Bug.20with.20let.20in.20pattern.20match

```lean
def h : ℕ → bool
| 0 := let _ := tt in tt
| (k+1) := k = k -- fails
--| (k+1) := if k = k then tt else ff -- fails
--| (k+1) := if h : k = k then tt else ff -- succeeds
```

The let in the first case seems to prevent type class resolution from finding decidable (k = k) in the second. Weirdly, if you use a dependent if and name the k = k hypothesis, it succeeds. It has to be a destructive `let`, i.e. `let a := tt in tt` succeeds.

Mario notes that `to_bool (k = k)` succeeds, pointing to something low-level going on.

Fixing this isn't high priority, just wanted to document what seems to be an unfamiliar bug.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by EdAyers** [comment]
The error happens if the elaborator performs `elaborator::visit_equations` (which happens for lets with patterns on LHS) twice.  They don't have to be nested, something in `visit_equations` or `visit_equation` is altering some state that escapes scope. The actual error only happens when the elaborator calls `mk_instance` and produces a metavariable for the typeclass instance. The problem is that the `decidable (k=k)` metavariable declaration's local context is not set properly or is altered somehow and so when it is synthesized at the end of `visit_equations`, the `k` in `decidable (k=k)` is not in the local context. The error doesn't occur with `to_bool (k = k)` or similar because in these cases the elaborator performs the synthesis step before the type_context pops `k` when it leaves `visit_equation`. This suggests that something about the first equation expression is setting the elaborator in to a weird state which causes a metavariable declaration's local context to not be set correctly.

This error can be removed by uncommenting some lines in `visit_equation` that perform a synthesis  before leaving, but this was likely commented out for a reason so it might cause some other things to break.

Here is a non-nested example:
```lean
example : bool :=
  let x := match 0 with y := ff end in
  match 0 with
  | k := k = k
  end
```

**Comment by EdAyers** [comment]
I've tracked down the issue: in `type_context.cpp`, at `type_context_old::mk_class_instance_at(lctx, type)`, if the `lctx` argument has the same frozen local instances then it just runs `mk_class_instance` without changing the local context. This is a bug because `lctx` can have different local consts to `this->m_lctx`. So the local const `k` is not in scope and so can't be unified.
