### ISSUE TITLE
Is there a way to get all the available tactics in Lean?

### ISSUE THREAD

**Issue by venom12138** [leanprover-community/lean#769]
Is there a way to get all the available tactics/lemma/theorems in Lean?

**Comment by PatrickMassot** [comment]
Thanks for your interest in Lean. This issue list is not the right place to ask user questions. This is a general principle with GitHub.

In this specific case, you should come to https://leanprover.zulipchat.com/ to discuss this. There you will learn about https://leanprover-community.github.io/ in general and https://leanprover-community.github.io/mathlib_docs/ in particular (assuming that you mean Lean 3 since you wrote your message here).
